/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rgu.gui;

import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.Date;
import rgu.AudioLanguage;
import rgu.Booking;
import rgu.BookingUtils;
import rgu.CityTour;
import rgu.TourAgent;
import rgu.TourPackage;
import rgu.Tourist;

/**
 *
 * @author ABIMBOLA JOHN OLADIPO
 * Create on : 11/23/2020
 * This is the main class that ties all the different class in the system into a functioning unit
 * This class maintain instances of the other class
 */
public class TourApp extends javax.swing.JFrame {
    /**
     * Creates new form TourApp
     */
    public TourApp() {
        initComponents();
        bookingUtils = new BookingUtils();
        bookedList = new ArrayList<>();
        touristList = new ArrayList<>();
        tourPackageList = new ArrayList<>();
        tourAgentsList = new ArrayList<>();
        guiTourist = new GUITourist(this);
        guiBookingList = new GUIBookingList(this, bookedList);
        guiTourPackage = new GUITourPackage(this);
        guiBooking = new GUIBooking(this);
        guiTourAgents = new GUITourAgents(this);
        services.setSelectedIndex(0);
        populateSystem();
    }

    private void populateSystem(){
        Tourist t = new Tourist("Dingxiang Cheng", "China", AudioLanguage.Chinese);
        TourAgent jack = new TourAgent("Jack Reacher", "Berlin");
        TourAgent hadley = new TourAgent("James Hadley Chase", "London");
        CityTour cityPackage = new CityTour(false, 0, "A tour of Hongcun Ancient Village. The 900-year-old village of Hongcun has long drawn in-the-know Chinese visitors, who love its tranquil vibe and distinctive architecture", "Anhui", 5000);
        Booking booking = new Booking(t, cityPackage, new Date());
        updateTouristList(t);
        updateTouristPackage(cityPackage);
        addBooking(booking);
        updateTourAgents(jack);
        updateTourAgents(hadley);
    }
    
    public void updateTouristList(Tourist tourist){
        touristList.add(tourist);
        guiBooking.updateTouristList(tourist);
        guiTourist.updateTouristList(tourist);
    }
    
    public void updateTourAgents(TourAgent agents){
        tourAgentsList.add(agents);
        guiTourAgents.updateTourAgentsList(agents);
    }
    
    public void updateTouristPackage(TourPackage tourPackage){
        tourPackageList.add(tourPackage);
        guiBooking.updateTourPackageList(tourPackage);
        guiTourPackage.updateTourPackages(tourPackage);
    }
    
    public void addBooking(Booking booking){
        bookedList.add(booking);
        guiBookingList.addBookings(booking);
        guiBooking.updateBookingList(booking);
    }
    
    public void removeBooking(Booking booking){
        bookedList.remove(booking);
        guiBookingList.removeBookings(booking);
        guiBooking.removeBookingList(booking);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        services = new javax.swing.JList<>();
        displayPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Tour App");

        services.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        services.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Create Booking", "View Bookings", "Create Tourists", "Tour Packages", "Tour Agents" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        services.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        services.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                servicesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(services);

        displayPane.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayPane, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
            .addComponent(displayPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public double[] viewTouristBill(Tourist t){
        return bookingUtils.calculateBill(bookedList, t);
    }
    
    private void servicesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_servicesValueChanged
        String value = services.getSelectedValue();
        displayPane.setVisible(false);
        switch (value){
            case "Create Booking":
                displayPane.removeAll();
                displayPane.add(guiBooking, BorderLayout.CENTER);
                displayPane.revalidate();
                break;
            case  "View Bookings":
                displayPane.removeAll();
                displayPane.add(guiBookingList, BorderLayout.CENTER);
                displayPane.revalidate();
                break;
            case "Tour Packages":
                displayPane.removeAll();
                displayPane.add(guiTourPackage, BorderLayout.CENTER);
                displayPane.revalidate();
                break;
            case "Create Tourists":
                displayPane.removeAll();
                displayPane.add(guiTourist, BorderLayout.CENTER);
                displayPane.revalidate();
                break;
            case "Tour Agents":
                displayPane.removeAll();
                displayPane.add(guiTourAgents, BorderLayout.CENTER);
                displayPane.revalidate();
                break;
        }
        displayPane.setVisible(true);
    }//GEN-LAST:event_servicesValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TourApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TourApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TourApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TourApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TourApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel displayPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> services;
    // End of variables declaration//GEN-END:variables
    private final ArrayList<Booking> bookedList;
    private final ArrayList<Tourist> touristList;
    private final ArrayList<rgu.TourPackage> tourPackageList;
    private final ArrayList<TourAgent> tourAgentsList;
    private final GUITourist guiTourist;
    private final GUIBookingList guiBookingList;
    private final GUITourPackage guiTourPackage;
    private final GUIBooking guiBooking;
    private final GUITourAgents guiTourAgents;
    private final BookingUtils bookingUtils;
}
